### PR TITLE
Adds PKI benchmarks from BoringSSL.

### PR DESCRIPTION
**Pull request by armfazh**
Adds a batch of benchmarks from BoringSSL.

### CODE REVIEW

**Comment by vkrasnov** [comment]
What does it bench that openssl doesn’t do better?

**Comment by armfazh** [comment]
> What does it bench that openssl doesn’t do better?

It's not intended to replace OpenSSL, but adding a different code base.

**Comment by vkrasnov** [comment]
But what is the value? What additional datapoint it provides? Just more of the same, we already have crypto from openssl and go.

**Comment by robdinh** [comment]
It's a datapoint that's more relevant for what we use. If there's a possibility that performance would show not the same compared to openssl, it's nice to know and look into that.

**Comment by vkrasnov** [comment]
@robdinh this is just the exact same datapoint, it will skew the suite to heavily towards crypto. OpenSSL is the best optimized for both Intel and ARM. Crypto is not using a lot of CPU on the edge, it is just a good proxy for the CPU capabilities. Moreover boringssl doesn't have a multi core mode.

**Pull request closed without merging**
